# Setup
title: Непізнаний простір
tagline: Веб-архів телеграм-каналу Непізнаний простір
url: https://neprostir.site
paginate: 10
baseurl: ""
permalink: :title/

kramdown:
    footnote_backlink: "&#10548;"

liquid:
  error_mode: warn

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts
  # - _data

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Vitalii Perehonchuk
  url: https://t.me/undead404
  email: brute18@gmail.com

# Custom vars
version: 1.3.0
github:
  repo: https://github.com/undead404/vast-space-unexplored
